from . import (
    AssignTranslator,
    BaseTranslator,
    CallTranslator,
    CommonTranslator,
    CreatelistTranslator,
    FunparaTranslator,
    FunretTranslator,
    GotoTranslator,
    IfTranslator,
    LabelTranslator,
    MulTranslator,
    ParaTranslator,
    RetTranslator,
)
